src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    const PER_PAGE = 9;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $excerpt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Image")
     */
    private $mainImage;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @MaxDepth(1)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="products")
     */
    private $tags;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tax")
     */
    private $taxes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductReference", mappedBy="product", orphanRemoval=true)
     */
    private $productReferences;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->taxes = new ArrayCollection();
        $this->productReferences = new ArrayCollection();
    }

    public function getMinUnitPriceIncludingTaxes(): float
    {
        $references = $this->getProductReferences();
        $min = $references[0]->getUnitPriceIncludingTaxes();
        foreach ($references as $reference) {
            if ($min > $reference->getUnitPriceIncludingTaxes()) {
                $min = $reference->getUnitPriceIncludingTaxes();
            }
        }

        return $min;
    }

    /**
     * @return Collection|ProductReference[]
     */
    public function getProductReferences(): Collection
    {
        return $this->productReferences;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->excerpt;
    }

    public function setExcerpt(?string $excerpt): self
    {
        $this->excerpt = $excerpt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMainImage(): ?Image
    {
        return $this->mainImage;
    }

    public function setMainImage(?Image $mainImage): self
    {
        $this->mainImage = $mainImage;

        return $this;
    }

    public function getCategory(): Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Tax[]
     */
    public function getTaxes(): Collection
    {
        return $this->taxes;
    }

    public function addTax(Tax $tax): self
    {
        if (!$this->taxes->contains($tax)) {
            $this->taxes[] = $tax;
        }

        return $this;
    }

    public function removeTax(Tax $tax): self
    {
        if ($this->taxes->contains($tax)) {
            $this->taxes->removeElement($tax);
        }

        return $this;
    }

    public function addProductReference(ProductReference $productReference): self
    {
        if (!$this->productReferences->contains($productReference)) {
            $this->productReferences[] = $productReference;
            $productReference->setProduct($this);
        }

        return $this;
    }

    public function removeProductReference(ProductReference $productReference): self
    {
        if ($this->productReferences->contains($productReference)) {
            $this->productReferences->removeElement($productReference);
            // set the owning side to null (unless already changed)
            if ($productReference->getProduct() === $this) {
                $productReference->setProduct(null);
            }
        }

        return $this;
    }
}

templates/_partials/alert.html.twig
<div class="alert alert-{{ type ?? 'success' }} alert-dismissible fade show mt-3">
    <i class="fas fa-exclamation-triangle mr-2"></i>
    {{ message | raw }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

templates/_partials/category.html.twig
{% set url = path('app_front_category_show', {
    categoryId: category.id,
    categorySlug: category.slug,
}) %}

<article class="category">
    <a href="{{ url }}">
        <img src="{{ category.image.urlThumbnail }}" class="category-image" alt="{{ category.label }}">
        <h3 class="category-title">{{ category.label }}</h3>
    </a>
</article>

templates/_partials/nav.html.twig
<nav class="navbar">
    <div class="navbar-header">
        <a href="{{ path('app_front_home_index') }}" class="nav-item nav-link nav-brandlink">Shop</a>
        <button id="navbar-toggle" class="navbar-toggle"><i class="fas fa-bars"></i></button>
    </div>

    <div class="navbar-collapse">
        <div class="nav-item">
            <a class="nav-link{{ active(app.request, 'app_front_category_index') }}"
               href="{{ path('app_front_category_index') }}">{% trans %}All categories{% endtrans %}</a>
        </div>

        {{ NavigationService.generateHtml() | raw }}

        <div class="nav-item nav-item-search">
            <input class="form-search-input" type="search" data-url="{{ path('app_front_home_search') }}">
        </div>

        {% if app.user %}
            <div class="nav-item">
                <a class="nav-link{{ active(app.request, 'app_front_user_profile') }}"
                   href="{{ path('app_front_user_profile') }}">{{ app.user.name }}</a>
            </div>

            <div class="nav-item">
                <a class="nav-link" href="{{ path('app_front_user_profile') }}">{% trans %}Logout{% endtrans %}</a>
            </div>
        {% endif %}

        {% if not app.user %}
            <div class="nav-item">
                <a class="nav-link btn btn-primary{{ active(app.request, 'app_auth_register') }}"
                   href="{{ path('app_auth_register') }}">{% trans %}Register{% endtrans %}</a>
            </div>

            <div class="nav-item">
                <a class="nav-link btn btn-login{{ active(app.request, 'app_auth_security_login') }}"
                   href="{{ path('app_auth_security_login') }}">{% trans %}Login{% endtrans %}</a>
            </div>
        {% endif %}

        <div id="cart-nav" class="nav-item nav-dropdown nav-item-cart"
             data-cart-items="{{ CartManager.items | json_encode(constant('JSON_FORCE_OBJECT')) }}"
             data-purchase-url="{{ path('app_front_purchase_purchase') }}"
             data-currency="{{ parameter('billing', 'currency').code }}">
        </div>
    </div>
</nav>

templates/_partials/navbar.html.twig
<nav class="navbar">
    <div class="navbar-header">
        <a href="{{ path('app_front_home_index') }}" class="nav-item nav-link nav-brandlink">Shop</a>
        <button id="navbar-toggle" class="navbar-toggle"><i class="fas fa-bars"></i></button>
    </div>

    <div class="navbar-collapse">
        <div class="nav-item">
            <a class="nav-link{{ active(app.request, 'app_front_category_index') }}"
               href="{{ path('app_front_category_index') }}">{% trans %}All categories{% endtrans %}</a>
        </div>

        {{ NavigationService.generateHtml() | raw }}

        <div class="nav-item nav-item-search">
            <input class="form-search-input form-control form-control-sm" type="search"
                   aria-label="{% trans %}Search{% endtrans %}"
                   data-url="{{ path('app_front_home_search') }}">
        </div>

        {% if app.user %}
            <div class="nav-item">
                <a class="nav-link{{ active(app.request, 'app_front_user_profile') }}" id="nav-link-profile"
                   href="{{ path('app_front_user_profile') }}">{{ app.user.name }}</a>
            </div>

            <div class="nav-item">
                <a class="nav-link btn btn-login"
                   href="{{ path('app_auth_security_logout') }}">{% trans %}Logout{% endtrans %}</a>
            </div>
        {% endif %}

        {% if not app.user %}
            <div class="nav-item">
                <a class="nav-link btn btn-primary{{ active(app.request, 'app_auth_register') }}"
                   href="{{ path('app_auth_register') }}">{% trans %}Register{% endtrans %}</a>
            </div>

            <div class="nav-item">
                <a class="nav-link btn btn-login{{ active(app.request, 'app_auth_security_login') }}"
                   href="{{ path('app_auth_security_login') }}">{% trans %}Login{% endtrans %}</a>
            </div>

            {% if app.environment == 'dev' %}
                <div class="nav-item">
                    <a class="nav-link btn btn-login{{ active(app.request, 'app_auth_security_usurp_index') }}"
                       href="{{ path('app_auth_security_usurp_index') }}">{% trans %}Usurp{% endtrans %}</a>
                </div>
            {% endif %}
        {% endif %}

        <div id="cart-nav" class="nav-item nav-dropdown nav-item-cart"
             data-cart-items="{{ CartManager.items | json_encode(constant('JSON_FORCE_OBJECT')) }}"
             data-purchase-url="{{ path('app_front_purchase_purchase') }}"
             data-currency="{{ parameter('billing', 'currency').code }}">
        </div>
    </div>
</nav>

templates/_partials/product.html.twig
{% set url = path('app_front_product_show', {
    productId: product.id,
    productSlug: product.slug,
    categoryId: product.category.id,
    categorySlug: product.category.slug,
}) %}
<article class="product">
    {% if product.mainImage %}
        <a href="{{ url }}">
            <img src="{{ product.mainImage.urlThumbnail }}" class="product-img-top" alt="{{ product.label }}">
        </a>
    {% endif %}
    <div class="product-body">
        <h3 class="product-title">
            <a href="{{ url }}">{{ product.label }}</a>
        </h3>

        <p class="product-price">
            {% trans %}From{% endtrans %}
            <span class="badge bg-secondary">{{ product.minUnitPriceIncludingTaxes | price }}</span>
        </p>
    </div>
</article>