src/Entity/Billing.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BillingRepository")
 * @ORM\Table(indexes={@Index(name="number_index", columns={"number"})})
 */
class Billing extends Orderable
{
    public const ORDERED_STATUS = 'ORDERED';
    public const DELIVRED_STATUS = 'DELIVRED';

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="billings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $addressText;

    /**
     * @ORM\Column(type="text")
     */
    private $addressLine1;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $addressLine2;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $addressPostalCode;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $addressCity;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $addressCountry;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $addressCountryCode;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=6)
     */
    private $addressLatitude;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=6)
     */
    private $addressLongitude;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $userEmail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $userName;

    public static function createFromCart(Cart $cart, int $currentNumber): self
    {
        return (new static)
            ->setDeliveryAddress($cart->getDeliveryAddress())
            ->setUser($cart->getUser())
            ->setNumber($cart->getCreatedAt()->format('Y-m') . '-' . $currentNumber)
            ->setStatus(self::ORDERED_STATUS)
            ->setComment($cart->getComment())
            ->setItemsCount($cart->getItemsCount())
            ->setTotalAmountExcludingTaxes($cart->getTotalAmountExcludingTaxes())
            ->setTotalAmountIncludingTaxes($cart->getTotalAmountIncludingTaxes());
    }

    public function setDeliveryAddress(?Address $deliveryAddress): Orderable
    {
        if ($deliveryAddress) {
            $this
                ->setAddressText($deliveryAddress->getText())
                ->setAddressLine1($deliveryAddress->getLine1())
                ->setAddressLine2($deliveryAddress->getLine2())
                ->setAddressPostalCode($deliveryAddress->getPostalCode())
                ->setAddressCity($deliveryAddress->getCity())
                ->setAddressCountry($deliveryAddress->getCountry())
                ->setAddressCountryCode($deliveryAddress->getCountryCode())
                ->setAddressLatitude($deliveryAddress->getLatitude())
                ->setAddressLongitude($deliveryAddress->getLongitude());
        }

        return parent::setDeliveryAddress($deliveryAddress);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBillingPath(): string
    {
        return "{$this->getUser()->getId()}/{$this->getNumber()}.pdf";
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this
            ->setUserEmail($user->getEmail())
            ->setUserName($user->getName())
            ->user = $user;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getAddressText(): ?string
    {
        return $this->addressText;
    }

    public function setAddressText(string $addressText): self
    {
        $this->addressText = $addressText;

        return $this;
    }

    public function getAddressLine1(): ?string
    {
        return $this->addressLine1;
    }

    public function setAddressLine1(string $addressLine1): self
    {
        $this->addressLine1 = $addressLine1;

        return $this;
    }

    public function getAddressLine2(): ?string
    {
        return $this->addressLine2;
    }

    public function setAddressLine2(?string $addressLine2): self
    {
        $this->addressLine2 = $addressLine2;

        return $this;
    }

    public function getAddressPostalCode(): ?string
    {
        return $this->addressPostalCode;
    }

    public function setAddressPostalCode(?string $addressPostalCode): self
    {
        $this->addressPostalCode = $addressPostalCode;

        return $this;
    }

    public function getAddressCity(): ?string
    {
        return $this->addressCity;
    }

    public function setAddressCity(?string $addressCity): self
    {
        $this->addressCity = $addressCity;

        return $this;
    }

    public function getAddressCountryCode(): ?string
    {
        return $this->addressCountryCode;
    }

    public function setAddressCountryCode(?string $addressCountryCode): self
    {
        $this->addressCountryCode = $addressCountryCode;

        return $this;
    }

    public function getAddressCountry(): ?string
    {
        return $this->addressCountry;
    }

    public function setAddressCountry(?string $addressCountry): self
    {
        $this->addressCountry = $addressCountry;

        return $this;
    }

    public function getAddressLatitude(): ?string
    {
        return $this->addressLatitude;
    }

    public function setAddressLatitude(?string $addressLatitude): self
    {
        $this->addressLatitude = $addressLatitude;

        return $this;
    }

    public function getAddressLongitude(): ?string
    {
        return $this->addressLongitude;
    }

    public function setAddressLongitude(?string $addressLongitude): self
    {
        $this->addressLongitude = $addressLongitude;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUserEmail()
    {
        return $this->userEmail;
    }

    public function setUserEmail(string $userEmail): self
    {
        $this->userEmail = $userEmail;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUserName()
    {
        return $this->userName;
    }

    public function setUserName(string $userName): self
    {
        $this->userName = $userName;

        return $this;
    }
}

src/Entity/OrderItem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderItemRepository")
 */
class OrderItem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $amountExcludingTaxes;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $amountIncludingTaxes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProductReference")
     * @ORM\JoinColumn(nullable=false)
     */
    private $productReference;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Orderable", inversedBy="items")
     * @ORM\JoinTable(name="orderable")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orderable;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getAmountExcludingTaxes(): ?string
    {
        return $this->amountExcludingTaxes;
    }

    public function setAmountExcludingTaxes(float $amountExcludingTaxes): self
    {
        $this->amountExcludingTaxes = $amountExcludingTaxes;

        return $this;
    }

    public function getPriceOfTaxes(): float
    {
        return $this->amountIncludingTaxes - $this->amountExcludingTaxes;
    }

    public function getAmountIncludingTaxes(): ?string
    {
        return $this->amountIncludingTaxes;
    }

    public function setAmountIncludingTaxes(float $amountIncludingTaxes): self
    {
        $this->amountIncludingTaxes = $amountIncludingTaxes;

        return $this;
    }

    public function getProductReference(): ProductReference
    {
        return $this->productReference;
    }

    public function setProductReference(?ProductReference $productReference): self
    {
        $this->productReference = $productReference;

        return $this;
    }

    public function getOrderable(): ?Orderable
    {
        return $this->orderable;
    }

    public function setOrderable(?Orderable $orderable): self
    {
        $this->orderable = $orderable;

        return $this;
    }
}

src/Entity/Orderable.php
<?php

namespace App\Entity;

use App\Services\Entity\Creatable;
use App\Services\Entity\Updatable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *  "cart" = "App\Entity\Cart",
 *  "billing" = "App\Entity\Billing"
 * })
 * @ORM\HasLifecycleCallbacks()
 */
abstract class Orderable
{
    use Updatable, Creatable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Address")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $deliveryAddress;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $itemsCount = 0;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    protected $totalAmountExcludingTaxes = 0;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    protected $totalAmountIncludingTaxes = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrderItem", mappedBy="orderable", orphanRemoval=true)
     * @var OrderItem[]|ArrayCollection
     */
    protected $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getDeliveryAddress(): ?Address
    {
        return $this->deliveryAddress;
    }

    public function setDeliveryAddress(?Address $deliveryAddress): self
    {
        $this->deliveryAddress = $deliveryAddress;

        return $this;
    }

    public function getIncludingTaxes()
    {
        return $this->totalAmountIncludingTaxes - $this->totalAmountExcludingTaxes;
    }

    public function getPriceOfTaxes()
    {
        return $this->totalAmountIncludingTaxes - $this->totalAmountExcludingTaxes;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(OrderItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $this->setItemsCount($this->getItemsCount() + 1);
            $this->setTotalAmountExcludingTaxes($this->getTotalAmountExcludingTaxes() + $item->getAmountExcludingTaxes());
            $this->setTotalAmountIncludingTaxes($this->getTotalAmountIncludingTaxes() + $item->getAmountIncludingTaxes());

            $item->setOrderable($this);
        }

        return $this;
    }

    public function getItemsCount(): ?int
    {
        return $this->itemsCount;
    }

    public function setItemsCount(int $itemsCount): self
    {
        $this->itemsCount = $itemsCount;

        return $this;
    }

    public function getTotalAmountExcludingTaxes(): ?string
    {
        return $this->totalAmountExcludingTaxes;
    }

    public function setTotalAmountExcludingTaxes(string $totalAmountExcludingTaxes): self
    {
        $this->totalAmountExcludingTaxes = $totalAmountExcludingTaxes;

        return $this;
    }

    public function getTotalAmountIncludingTaxes(): ?float
    {
        return $this->totalAmountIncludingTaxes;
    }

    public function setTotalAmountIncludingTaxes(string $totalAmountIncludingTaxes): self
    {
        $this->totalAmountIncludingTaxes = $totalAmountIncludingTaxes;

        return $this;
    }

    public function removeItem(OrderItem $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);

            $this->setItemsCount($this->getItemsCount() - 1);
            $this->setTotalAmountExcludingTaxes($this->getTotalAmountExcludingTaxes() - $item->getAmountExcludingTaxes());
            $this->setTotalAmountIncludingTaxes($this->getTotalAmountIncludingTaxes() - $item->getAmountIncludingTaxes());


            // set the owning side to null (unless already changed)
            if ($item->getOrderable() === $this) {
                $item->setOrderable(null);
            }
        }

        return $this;
    }
}

src/Controller/Front/BillingController.php
<?php

namespace App\Controller\Front;

use App\Entity\Billing;
use App\Services\Shop\Bank\BillingService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/billings", name="app_front_billing_")
 */
class BillingController extends AbstractController
{
    /**
     * @Route("/export/{billingNumber}", name="export", methods={"GET"})
     * @Entity("billing", expr="repository.getWithAllRelations(billingNumber)")
     * @IsGranted(App\Security\Voter\BillingVoter::EXPORT, subject="billing")
     */
    public function export(
        Billing $billing,
        Request $request,
        BillingService $billingService
    ) {
        $pdfPath = $billingService->getPdfPath($billing);

        if ($request->query->getInt('force') === 1 || $pdfPath === null) {
            $pdfPath = $billingService->generatePdf($billing);
        }

        return new BinaryFileResponse($pdfPath);
    }
}

templates/billing/show.html.twig
{% extends "_layouts/pdf.html.twig" %}

{% block title %}
    {% trans %}Billing{% endtrans %}: {{ billing.number }}
{% endblock %}

{% block body %}
    <div class="container my-5">
        <div class="row">
            <div class="col">
                <p>
                    <strong>Shop</strong><br>
                    {{ parameter('billing', 'address').line1 }} <br>
                    {% if parameter('billing', 'address').line2 %}
                        {{ parameter('billing', 'address').line2 }}<br>
                    {% endif %}
                    {{ parameter('billing', 'address').postal_code }} {{ parameter('billing', 'address').city }}
                    {{ parameter('billing', 'address').country }}<br>
                    <br>
                </p>
                <p>
                    <i class="fas fa-phone"></i> {{ parameter('billing', 'phone_number') }}
                </p>
            </div>
        </div>

        <div class="row">
            <div class="offset-6 col text-right">
                <strong>{{ billing.user.name }}</strong><br>
                {{ billing.addressLine1 }}<br>
                {% if billing.addressLine2 %}
                    {{ billing.addressLine2 }}
                {% endif %}
                {{ billing.addressPostalCode }} {{ billing.addressCity }}<br>
                {{ billing.addressCountry }}
            </div>
        </div>

        <p class="lead">
            {% trans %}Billing number{% endtrans %}: {{ billing.number }}<br>
            {% trans %}Billing date{% endtrans %}: {{ billing.updatedAt | date('d F Y') }}
        </p>

        <table class="table my-5">
            <thead>
            <tr>
                <th>{% trans %}Description{% endtrans %}</th>
                <th>{% trans %}Quantity{% endtrans %}</th>
                <th>{% trans %}Unit price{% endtrans %}</th>
                <th>{% trans %}Taxes{% endtrans %}</th>
                <th>{% trans %}Total amount including taxes{% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for item in billing.items %}
                <tr>
                    <td>{{ item.productReference.label }}</td>
                    <td>{{ item.quantity }}</td>
                    <td class="text-right">{{ item.productReference.unitPriceExcludingTaxes | price }}</td>
                    <td class="text-right">{{ item.priceOfTaxes | price }}</td>
                    <td class="text-right">{{ item.amountIncludingTaxes | price }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot class="header-cart-total">
            <tr>
                <td class="border-0" colspan="4">{% trans %}Total amount excluding taxes{% endtrans %} :</td>
                <td class="border-0">{{ billing.totalAmountExcludingTaxes | price }}</td>
            </tr>
            <tr class="header-cart-total-vat">
                <td class="border-0" class="text-right" colspan="4">{% trans %}Including taxes{% endtrans %}</td>
                <td class="border-0">{{ billing.includingTaxes | price }}</td>
            </tr>
            <tr style="font-size: 1.5rem;">
                <td class="border-0" class="text-right"
                    colspan="4">{% trans %}Total amount including taxes{% endtrans %} :
                </td>
                <td class="border-0">{{ billing.totalAmountIncludingTaxes | price }}</td>
            </tr>
            </tfoot>
        </table>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores exercitationem iusto quis repudiandae
            sapiente? Ab aliquid consequatur cupiditate deleniti, eum illum laborum maxime, mollitia, nam nobis non
            officiis saepe voluptatem.
        </p>
    </div>
{% endblock %}